# Generated by Django 4.2.2 on 2023-06-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='DOI',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='PDF_Link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
